layers:
  - name: models
    collectors:
      - type: class_inherits
        base_class: "django.db.models.Model"
        exclude_files_regex: ".*\\.venv/.*"

  - name: views
    collectors:
      - type: file_regex
        regex: ".*/views_api.py"
        exclude_files_regex: ".*\\.venv/.*"

ruleset:
  views:
    disallow:
      - models
