paths:
  - /path/to/your/project

exclude_files:
  - ".*\\.venv/.*"

layers:
  - name: models
    collectors:
      - type: class_inherits
        base_class: "django.db.models.Model"

  - name: views
    collectors:
      - type: file_regex
        regex: ".*/views_api.py"

  - name: app1
    collectors:
      - type: directory
        directories:
          - "app1"

  - name: services
    collectors:
      - type: class_name_regex
        class_name_regex: ".*Service$"
        exclude_files_regex: ".*excluded_folder_name.*"

  - name: auth_protected
    collectors:
      - type: decorator_usage
        decorator_name: "login_required"

ruleset:
  views:
    disallow:
      - models
